Basic api contract without implementation
Softo-kurmiai/CookEase pull request #16
Opened 2024-05-01 13:52 UTC by ignasvoveriukas9

Tried to add api controllers without implementation to make an api contract

2024-05-01 16:28 UTC, LBrasiunas commented on Server/Application/DTOs/Collection/CollectionCreateRequest.cs
> +    public required string description { get; set; }
All properties should be in PascalCase.

2024-05-01 16:31 UTC, LBrasiunas requested changes
Check comment.

2024-05-10 12:42 UTC, AndriusPau approved these changes

2024-05-14 19:28 UTC, LBrasiunas approved these changes

2024-05-14 19:37 UTC, merged