Added user controller with crud operations.
Softo-kurmiai/CookEase pull request #5
Opened 2024-04-22 11:03 UTC by ignasvoveriukas9

Added user controller with crud operations. Currently UserService dosn't have proper implementation.

2024-04-22 21:38 UTC, LBrasiunas commented on Server/Application/Services/UserService.cs
> +    }
Create interfaces as a seperate file inside a folder `Interfaces`.

2024-04-22 21:39 UTC, LBrasiunas commented on Server/Application/Services/UserService.cs
> +        public List<UserDTO> GetAll()
The `GetAll` method will need some sort of pagination (e.g. take count per page, page number).

2024-04-22 21:40 UTC, LBrasiunas commented on Server/Application/Services/UserService.cs
> +            }else
Try to be consistent with your linting of code.

2024-04-22 21:42 UTC, LBrasiunas commented on Server/CookEase.Api/Controllers/UserController.cs
> +        private readonly ILogger<WeatherForecastController> _logger;
Generally we don't put loggers inside of controllers. We can add them inside of services.

2024-04-22 21:43 UTC, LBrasiunas commented on Server/CookEase.Api/Controllers/UserController.cs
> +            return users;
You set the return type of this endpoint as `ActionResult`. It should then be like this `return Ok(users);`

2024-04-22 21:44 UTC, LBrasiunas commented on Server/CookEase.Api/Controllers/UserController.cs
> +                return NotFound("User not found");
Try to not use single line `if` statements and add parentheses {} also if you are just gonna put a single line of code.

2024-04-22 21:45 UTC, LBrasiunas commented on Server/CookEase.Api/Controllers/UserController.cs
> +        public ActionResult<UserDTO> Post([Required] UserDTO user)
I believe you should also use the `[FromBody]` annotation.

2024-04-22 21:45 UTC, LBrasiunas commented on Server/CookEase.Api/Controllers/UserController.cs
> +        public ActionResult<UserDTO> Update([Required] UserDTO user)
Same here as previously.

2024-04-23 16:50 UTC, LBrasiunas commented on Server/CookEase.Api/Controllers/UserController.cs
> +            }
To overcome this we will need to use two different DTOs - one more a request (`POST` or `PUT`) and another for the whole DB entity response.

2024-04-23 16:54 UTC, LBrasiunas commented on Server/Application/Services/UserService.cs
>              }
For future, use all parentheses on a new line. Don't try to save code lines as this way it is easier to find the beggining and end of a code block.

2024-04-23 16:55 UTC, LBrasiunas commented on Server/Application/Services/UserService.cs
> +namespace Application.Services {
Check about file-scoped namespaces. This will reduce code nesting with additional parentheses. I believe it is possible to do it with `Ctrl`+`.`

2024-04-23 16:58 UTC, LBrasiunas commented on Server/Application/Interfaces/IUserService.cs
> +        UserDTO? Update(UserDTO userDTO);
This is a perfect place to use two different DTOs - `UserResponse` and `UserRequest` with the only difference between them is the response having the `Id` property.

2024-04-23 17:01 UTC, LBrasiunas commented on Server/CookEase.Api/Controllers/UserController.cs
> +        public ActionResult<List<UserDTO>> GetAll(int? countPerPage, int? page) {
There is a useful annotation included in ASP.NET `[ProducesResponseType]` it helps identify which status codes the endpoint produces whilst being in Swagger.

2024-04-23 17:03 UTC, LBrasiunas commented on Server/Application/Interfaces/IUserService.cs
> +        List<UserDTO> GetAll(int? countPerPage, int? page);
You can define default values to not make them nullable (e.g. `int countPerPage = 20, int page = 1`)

2024-04-23 17:05 UTC, LBrasiunas requested changes
Check out the comments that I have provided.

2024-04-23 17:47 UTC, LBrasiunas approved these changes
Check out the latest changes.

2024-04-23 18:01 UTC, ignasvoveriukas9 reviewed
Looks good

2024-04-23 18:01 UTC, merged